### ISSUE TITLE
Playing / Pause Sensor

### ISSUE THREAD

**Issue by dampney** [maxileith/homebridge-airport-express-connected#200]
### Current Situation

Plug-in works well - I’ve successfully integrated the speaker sensors into my automations so motion in certain rooms will play certain ambient sounds depending on time/day/weather/etc (when Airplay is off).

Would love to see a second sensor (motion sensor) for when the AirPort Express is playing (detected) or paused/stopped (not detected) so automations won’t restart playing sounds every few minutes when motion is detected again.

### Proposed Change

Second sensor for AirPort Express playing / paused.

### Additional Context

Alternative solution: I could possibly add a dummy sensor from another plug-in to my automations so when each AirPort Express plays the sensor detects/turns on but I was hoping this functional plug-in could do the trick all in one package if possible?

**Comment by maxileith** [comment]
Unfortunately, the critera whether or not something is playing is not exposed via mDNS.
